import Navbar from "@/components/administrator/Navbar"
import Head from "next/head"

const Portfolio = () => {
    return (
        <>
            <Head>
                <title>Portfolio | Administrator</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta property="og:description" name="description" content="Website Pribadi Diamsyah M Dida, Dibuat Dengan Vue JS v3. Diamsyah M Dida atau Dida Mustofa Diamsyah adalah seorang programmer yang sudah berkecimpung di dunia pemrograman selama lebih dari 3 tahun, dan terbiasa menggunakan bahasa program PHP dan Javascript." key="description" />
                <meta property="og:keywords" name="keywords" content="Website Pribadi Diamsyah M Dida, Website Diamsyah, Website Dida, Diamsyah M Dida, Dida, Dida Mustofa, Dida Mustofa Diamsyah" key="keywords" />
                <meta property="og:author" name="author" content="Diamsyah M Dida" key="author" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Navbar />
            </main>
        </>
    )
}

export default Portfolio